== Imposta sul valore aggiunto (IVA)

I capitoli seguenti descrivono le diverse informazioni in materia dell'IVA che possono essere fornite in una fattura PEPPOL o in una nota di credito.

Si consiglia per ulteriori dettagli di consultare anche i codici di categoria IVA presenti nella codifica di riferimento di categoria IVA ed il calcolo dell'IVA per una rappresentazione più dettagliata ed esempi su come eseguire i calcoli per la ripartizione IVA.

=== Informazioni IVA su riga

Ogni riga della fattura deve avere il codice della categoria IVA riferita alla voce fatturata (BT-151) e per tutte le categorie IVA, eccetto "Non soggetto ad IVA" (O), deve essere fornita l'aliquota IVA.

=== Sconti e maggiorazioni a livello di testata

Ogni sconto e maggiorazione a livello di testata deve avere il codice di categoria IVA identificati da BT-95 e BT-102. Per tutte le categorie IVA, eccetto "Non soggetto ad IVA" (O), deve essere fornita l'aliquota IVA.

=== Ripartizione IVA

Ci sono 4 principali categorie IVA per una fattura:

**1.**	**Fuori campo IVA** se la fattura non rientra nella legislazione IVA, non vi sono informazioni da indicare in fattura.

**2.**	**Non imponibili IVA**
se la fattura ha degli articoli con aliquota IVA a zero è necessario indicare nella categoria di imposta (CategoryID) il valore ‘Z’. 

**3.**	**Esente IVA**
se la fattura ha degli articoli che sono esenti IVA è necessario indicare il valore ‘E’ nel CategoryID di questi articoli. In aggiunta dovrebbe essere fornita la ragione per l’esenzione.

**4.**	**IVA normale**
per merce o servizi relativi ad una categoria VAT normale è possibile specificare se si tratta di un aliquota standard, superiore o inferiore.

Per tutti i casi di fatture esenti o fuori del campo di applicazione IVA, la categoria IVA deve essere fornita a livello di riga come pure per ogni sconto e maggiorazione a livello di testata.


Si consiglia di osservare che per l'aliquota dell'IVA dovrebbero essere considerate solo i decimali significativi, i.e. qualsiasi differenza in termini di cifre decimali non deve determinare differenti valori dell'IVA.

====
*Riga 1* contiene codice categoria = *S* e aliquota IVA = *22*

*Riga 2* contiene codice categoria = *S* e aliquota IVA = *22.00*

Questo dovrebbe comportare una sola ripartizione dell'IVA.
====
